<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "axkirchenplaner"
 *
 * Auto generated by Extension Builder 2016-11-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/
$EM_CONF['axkirchenplaner'] = [
	'title' => 'Kirchenplaner',
	'description' => 'Kirchenplaner Extension for API usage of qsp.portal.de',
	'category' => 'plugin',
	'author' => '',
	'author_email' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '3.0.1',
	'autoload' => [
		"psr-4" => [
            "Axist\\AxKirchenplaner\\" => "Classes"
		]
	],
	'constraints' => [
		'depends' => [
			'typo3' => '14.0.0-14.99.99'
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];
