services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Axist\AxKirchenplaner\:
    resource: '../Classes/*'

  Axist\AxKirchenplaner\Hook\AddCustomFieldsToFlexFormHook:
    public: true
